### ISSUE TITLE
IBEX assertion failure

### ISSUE THREAD

**Issue by nnarodytska** [dreal/dreal3#77]
```
(gdb) run ../../src/tests/nra/01.smt2
Starting program: /home/nina/workspace/dreal3_nina/dreal3/builds/eclipse-debug/dReal ../../src/tests/nra/01.smt2
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Solution:
x : [2.4, 2.600000000000001] = [2.4, 2.40078125]
y : [-10, 10] = [-0.7379211960626793, -0.7373937155412443]
dReal: ../src/arithmetic/ibex_TemplateVector.cpp_:75: V1& ibex::{anonymous}::_assign(V1&, const V2&) [with V1 = ibex::IntervalVector; V2 = ibex::IntervalVector]: Assertion `v.size()==x.size()' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff6de8cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6de8cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6dec0d8 in __GI_abort () at abort.c:89
#2  0x00007ffff6de1b86 in __assert_fail_base (fmt=0x7ffff6f333d0 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0xdd0995 "v.size()==x.size()", 
    file=file@entry=0xdd08d8 "../src/arithmetic/ibex_TemplateVector.cpp_", line=line@entry=75, 
    function=function@entry=0xdd0f40 <ibex::IntervalVector& ibex::(anonymous namespace)::_assign<ibex::IntervalVector, ibex::IntervalVector>(ibex::IntervalVector&, ibex::IntervalVector const&)::__PRETTY_FUNCTION__> "V1& ibex::{anonymous}::_assign(V1&, const V2&) [with V1 = ibex::IntervalVector; V2 = ibex::IntervalVector]") at assert.c:92
#3  0x00007ffff6de1c32 in __GI___assert_fail (assertion=0xdd0995 "v.size()==x.size()", file=0xdd08d8 "../src/arithmetic/ibex_TemplateVector.cpp_", line=75, 
    function=0xdd0f40 <ibex::IntervalVector& ibex::(anonymous namespace)::_assign<ibex::IntervalVector, ibex::IntervalVector>(ibex::IntervalVector&, ibex::IntervalVector const&)::__PRETTY_FUNCTION__> "V1& ibex::{anonymous}::_assign(V1&, const V2&) [with V1 = ibex::IntervalVector; V2 = ibex::IntervalVector]") at assert.c:101
#4  0x00000000008fded1 in ibex::(anonymous namespace)::_assign<ibex::IntervalVector, ibex::IntervalVector> (v=..., x=...) at ../src/arithmetic/ibex_TemplateVector.cpp_:75
#5  0x00000000008fd7e6 in ibex::IntervalVector::operator= (this=0x11c7128, x=...) at ../src/arithmetic/ibex_IntervalVector.cpp:264
#6  0x0000000000864098 in dreal::box::operator= (this=0x11c7110) at /home/nina/workspace/dreal3_nina/dreal3/src/util/box.h:37
#7  0x00000000008606eb in dreal::nra_solver::popBacktrackPoint (this=0x11c6fa0) at /home/nina/workspace/dreal3_nina/dreal3/src/dsolvers/nra_solver.cpp:255
#8  0x00000000007fd6c8 in Egraph::popBacktrackPoint (this=0x11bb210) at /home/nina/workspace/dreal3_nina/dreal3/src/opensmt/egraph/EgraphSolver.C:496
#9  0x000000000085b364 in THandler::backtrack (this=0x11c4a10) at /home/nina/workspace/dreal3_nina/dreal3/src/opensmt/tsolvers/THandler.C:223
#10 0x00000000008399b5 in CoreSMTSolver::cancelUntil (this=0x11bba90, level=-1) at /home/nina/workspace/dreal3_nina/dreal3/src/opensmt/smtsolvers/CoreSMTSolver.C:422
#11 0x000000000083e5ff in CoreSMTSolver::solve (this=0x11bba90, assumps=..., max_conflicts=0) at /home/nina/workspace/dreal3_nina/dreal3/src/opensmt/smtsolvers/CoreSMTSolver.C:1912
#12 0x000000000084711b in SimpSMTSolver::solve (this=0x11bba90, assumps=..., conflicts=0, do_simp=true, turn_off_simp=false) at /home/nina/workspace/dreal3_nina/dreal3/src/opensmt/smtsolvers/SimpSMTSolver.C:323
#13 0x0000000000846f2a in SimpSMTSolver::solve (this=0x11bba90, assumps=..., do_simp=true, turn_off_simp=false) at /home/nina/workspace/dreal3_nina/dreal3/src/opensmt/smtsolvers/SimpSMTSolver.C:210
#14 0x00000000007ed905 in SimpSMTSolver::solve (this=0x11bba90, do_simp=true, turn_off_simp=false) at /home/nina/workspace/dreal3_nina/dreal3/src/opensmt/smtsolvers/SimpSMTSolver.h:211
#15 0x00000000007ed8c8 in SimpSMTSolver::smtSolve (this=0x11bba90, do_simp=true) at /home/nina/workspace/dreal3_nina/dreal3/src/opensmt/smtsolvers/SimpSMTSolver.h:55
#16 0x00000000007eaa1f in OpenSMTContext::staticCheckSAT (this=0x7fffffffd4e0) at /home/nina/workspace/dreal3_nina/dreal3/src/opensmt/api/OpenSMTContext.C:468
#17 0x00000000007ea245 in OpenSMTContext::executeStatic (this=0x7fffffffd4e0) at /home/nina/workspace/dreal3_nina/dreal3/src/opensmt/api/OpenSMTContext.C:330
#18 0x00000000007e9ad2 in OpenSMTContext::executeCommands (this=0x7fffffffd4e0) at /home/nina/workspace/dreal3_nina/dreal3/src/opensmt/api/OpenSMTContext.C:203
#19 0x00000000007df068 in main (argc=2, argv=0x7fffffffd7c8) at /home/nina/workspace/dreal3_nina/dreal3/src/main.cpp:172
```

**Comment by soonhokong** [comment]
Hey @nnarodytska, I finally reproduce the problem on my machine. I'll fix it soon.

**Comment by soonhokong** [comment]
3f37f79d85dca8782f83ea434098e6d8b381c803 fixes the problem. It's not ideal yet. I'll refactor this later.
